@startuml
title UML-діаграма класів: Метеосервіс

abstract class УчасникМетеосистеми {
  - id : int
  - name : string
  + УчасникМетеосистеми(id:int, name:string)
  + getName() : string
}

interface IПланСповіщень {
  + сформуватиСповіщення() : string
}

class Метеоролог {
  - спеціалізація : string
  + Метеоролог(id:int, name:string, спец:string)
  + публікуватиПрогноз() : void
  + публікуватиПопередження() : void
  + аналізуватиТочність() : void <<final>>
}

class Технік {
  - рівень : string
  + Технік(id:int, name:string, рівень:string)
  + обслуговуватиСенсори() : void
  + обслуговуватиРадар() : void
}

class Попередження {
  - текст : string
  - час : Date
  + Попередження(текст:string, час:Date)
  + getDetails() : string
}

class ПорігПодії {
  - рівеньОпасності : int
  + ПорігПодії(level:int)
}

class Регіон {
  - назва : string
  + Регіон(назва:string)
  + додатиПопередження(п:Попередження) : void
}

class СервісСповіщень {
  - адресати : List<string>
  + СервісСповіщень()
  + надіслати(текст:string) : bool
}

УчасникМетеосистеми <|-- Метеоролог
УчасникМетеосистеми <|-- Технік

Метеоролог ..|> IПланСповіщень
Технік ..|> IПланСповіщень

Попередження ..> СервісСповіщень
Регіон o-- Попередження
Попередження *-- ПорігПодії
@enduml
